def decode_with_beam_search(encoder, decoder, k=3):
    """Generate captions with Beam Search.
    Input:
        encoder: encoder model
        decoder: decoder model
        features: features generated by encoder model
        k: select top-k candidates (default = 3)
    """
    # TODO